const componentsDarkTheme = {
  klerosUIComponentsName: "dark",
  klerosUIComponentsPrimaryPurple: "#7E1BD4",
  klerosUIComponentsSecondaryPurple: "#C5ABFF",
  klerosUIComponentsMediumPurple: "#390F6C",
  klerosUIComponentsLightPurple: "#FCFBFF",
  klerosUIComponentsPrimaryBlue: "#6CC5FF",
  klerosUIComponentsSecondaryBlue: "#7186FF",
  klerosUIComponentsMediumBlue: "#0A0A0A",
  klerosUIComponentsLightBlue: "#050505",
  klerosUIComponentsPrimaryText: "#FFFFFF",
  klerosUIComponentsSecondaryText: "#BEBEC5",
  klerosUIComponentsTertiaryText: "#989AA0",
  klerosUIComponentsStroke: "#FFFFFF1A",
  klerosUIComponentsLightGrey: "#0A0A0A",

  klerosUIComponentsWhiteBackground: "#000000",
  klerosUIComponentsLightBackground: "#000000",

  klerosUIComponentsDefaultShadow: "#00000000",
  klerosUIComponentsHoveredShadow: "#FFFFFF1A",

  klerosUIComponentsSuccess: "#65DC7F",
  klerosUIComponentsSuccessLight: "#0A0A0A",
  klerosUIComponentsWarning: "#FFC46B",
  klerosUIComponentsWarningLight: "#0A0A0A",
  klerosUIComponentsError: "#FF5A78",
  klerosUIComponentsErrorLight: "#0A0A0A",
  klerosUIComponentsTint: "#DDB6FF",
  klerosUIComponentsTintMedium: "#0A0A0A",
  klerosUIComponentsTintPurple: "#050505",
  klerosUIComponentsTintYellow: "#FFE16B",

  klerosUIComponentsSkeletonBackground: "#0A0A0A",
  klerosUIComponentsSkeletonHighlight: "#1A1A1A",

  klerosUIComponentsTransitionSpeed: "0.25s",
};


export const darkTheme = {
  ...componentsDarkTheme,
  name: "dark",
  white: "#FFFFFF",
  black: "#000000",
  primaryPurple: "#7E1BD4",
  secondaryPurple: "#C5ABFF",
  darkPurple: "#000000",
  mediumPurple: "#390F6C",
  lightPurple: "#FCFBFF",
  violetPurple: "#6A1DCD",
  lavenderPurple: "#BB72FF",
  primaryBlue: "#6CC5FF",
  secondaryBlue: "#7186FF",
  mediumBlue: "#0A0A0A",
  primaryText: "#FFFFFF",
  secondaryText: "#BEBEC5",
  tertiaryText: "#989AA0",
  stroke: "#FFFFFF1A",
  lightGrey: "#0A0A0A",

  whiteBackground: "#000000",
  lightBackground: "#000000",
  backgroundTwo: "#0A0A0A",

  defaultShadow: "#00000000",
  hoveredShadow: "#FFFFFF1A",
  whiteLowOpacitySubtle: "#FFFFFF0F",
  whiteLowOpacityStrong: "#FFFFFF24",
  blackLowOpacity: "#00000080",

  success: "#65DC7F",
  successLight: "#0A0A0A",
  warning: "#FFC46B",
  warningLight: "#0A0A0A",
  error: "#FF5A78",
  errorLight: "#0A0A0A",
  tint: "#DDB6FF",
  tintMedium: "#0A0A0A",
  tintPurple: "#E5D6FF",
  tintYellow: "#FFE16B",

  transitionSpeed: "0.25s",

  skeletonBackground: "#0A0A0A",
  skeletonHighlight: "#1A1A1A",

  paleCyan: "#ACFFFF",
  limeGreen: "#F3FFD9",
};
